# -*- coding: utf-8 -*-
"""gtts_Text2SpeechLIB.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HGe8aPhs0FTblcbTMgwSZUZjO8eBvIm-
"""

!pip install --upgrade gTTS
from gtts import gTTS

help(gTTS)

myobj1 = gTTS(text= "Olá, Professor Eduardo", lang='pt', slow=False)
name1 = "du.mp3"
myobj1.save(name1)   #Saving the converted audio in a mp3 file
# Playing the converted file
audio_file = open(name1, 'rb')
#audio_bytes = audio_file.read()
#st.audio(audio_bytes, format='audio/ogg',start_time=0)

!pip install pygame

from pygame import mixer, time

mixer.pre_init(44100, -16, 2, 2048)
mixer.init()

data = open('\teste01.mp3', 'rb').read()
sound = mixer.Sound(buffer=data)

audio = sound.play()
while audio.get_busy():
    time.Clock().tick(10)